### ISSUE TITLE
ECP without any core electrons

### ISSUE THREAD

**Issue by Konjkov** [dceresoli/PStudio#1]
Hello Davide.
I need to create a HF pseudo potential for correlated electron systems without any core electrons, as described in
"Smooth relativistic Hartree–Fock pseudopotentials for H to Ba and Lu to Hg" J. R. Trail and R. J. Needs DOI: 10.1063/1.1888569.
It is also important that the pseudopotential does not have singularities at the nuclear site.
Сan your code perform such a task?

Best Vladimir

**Comment by dceresoli** [comment]
Dear Vladimir,
this code can't perform HF calculations yet. I'm not an expert, but up to now, the pseudo-potentials V_l(r) can be constructed to be non singular at the nucleus, depending on the method. Not sure about HF.
Best wishes,
D.
